[workspace]
channels = ["conda-forge", "auto-mech"]
name = "pes"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[dependencies]
autochem = ">=0.2025.0,<0.2026"
ipykernel = ">=7.1.0,<8"
python = "<3.14"
rdkit = ">=2025.9.4,<2026"
networkx = ">=3.6.1,<4"
py3dmol = ">=2.5.3,<3"
matplotlib = ">=3.10.8,<4"
sqlmodel = ">=0.0.32,<0.0.33"
